### ISSUE TITLE
Encapsulated package breaks the gateway

### ISSUE THREAD

**Issue by trivialkettle** [commschamp/cc.mqttsn.libs#17] opened 2024-08-27 12:54 UTC
Hi,
when I send the following encapsulated package to the gateway

```
09 fe 00 d4 3e 27 6e 03  | ....>'n.
c3 1e 04 04 01 00 0a 64  | .......d
6f 6e 67 6c 65 2d 44 34  | ongle-D4
3a 33 45 3a 32 37 3a 36  | :3E:27:6
45 3a 30 33 3a 43 33     | E:03:C3
```

the gateway crashes with the message

```
$ cc_mqttsn_gateway_app -c ./gateway.conf
[INFO]: New UDP client connection from: 127.0.0.1:45576
cc_mqttsn_gateway_app: /xxx/cc.mqttsn.libs/gateway/app/gateway/GatewaySession.cpp:58: bool cc_mqttsn_gateway_app::GatewaySession::start(): Assertion `m_termReqCb' failed.
```

This is the first package my forwarder sends, so it did not connect or anything before.

Thanks for you help.

**Comment by arobenko** [comment] 2024-08-27 23:22
Please retry with "develop" branch.
At this stage there the gateway application creates a connection to a broker for every "session". When the packet arrives and not parsed yet, it is considered to be a legit client and a Session object is create for it, which initiates connection to a broker. When the message is parsed new "encapsulated" Session object is created and also initiates a connection to the broker. Due to the fact the the first Session object doesn't really send any data to a broker, the latter closes the connection, while the gateway application re-opens it again. As the result there is a constant loop of creating and closing one redundant connection to a broker.

I will work on making the connection to a broker being a "lazy" one, i.e. established only when there is a data to be sent to a broker.

**Comment by arobenko** [comment] 2024-08-28 10:24
Thanks, I appreciate your help. My ability to properly test the forwarding encapsulation support is limited. I kind of reluctant and don't have much time to implement proper forwarding application to be able to reproduce problems in my environment.

I've added some extra assert statements to the GatewaySession.cpp (on develop branch) which might help detect the problem. I won't have much time tomorrow, but on Friday I think I'll introduce the lazy broker connection I mentioned. After that it should be easier to get to the bottom of it.

**Comment by arobenko** [comment] 2024-08-28 10:55
I think I know what the problem is, please try updated "develop" branch again.

**Comment by arobenko** [comment] 2024-08-28 11:34
I was talking about the crash / assert. I'll continue to work on it on
Friday

**Comment by arobenko** [comment] 2024-09-01 01:35
I've added an ability to emulate encapsulated session to the pub / sub client applications.

- Emulating sub client
```
./cc_mqttsn_client_sub -c client1 -t "#" --fwd-enc-node-id "\x00\x01"
```
The output from the gateway is:
```
[INFO]: New UDP client connection from: 127.0.0.1:38853
[INFO]: (0x614000000040) New primary session
[INFO]: (0x614000000240) New encapsulated session
[INFO]: (0x614000000240) Connected client: client1
```
Add two "pub" clients sending from the same port but claiming different node IDs:
```
./cc_mqttsn_client_pub -c client2 -t "bla" -m "hello" -P 20000 --pub-no-disconnect --fwd-enc-node-id "\x00\x02"
./cc_mqttsn_client_pub -c client3 -t "bla" -m "hello" -P 20000 --pub-no-disconnect --fwd-enc-node-id "\x00\x03"
```
The output from the gateway is:
```
[INFO]: (0x614000000440) New primary session
[INFO]: (0x614000000640) New encapsulated session
[INFO]: (0x614000000640) Connected client: client2
[INFO]: (0x614000000840) New encapsulated session
[INFO]: (0x614000000840) Connected client: client3
```
After a while when keep-alive value expires the "publish" clients are disconnected by the broker:
```
[INFO]: (0x614000000640) Terminating session for client: client2
[INFO]: (0x614000000840) Terminating session for client: client3
[INFO]: (0x614000000440) Terminating session for client: 
[INFO]: Terminated UDP client connection from: 127.0.0.1:20000
```

Everything seems to be working as expected, no unexpected termination from the broker.
Also note, that previously I hard-coded the "radius" value in the forwarding encapsulation header to be "3". Maybe your forwarder didn't like it and did some unexpected stuff with it. Now I removed it and it's value became "0". Please retry again. If the problem persists you need to run a thorough traffic analysis on your setup and see if there are any discrepancies.

**Comment by arobenko** [comment] 2024-09-03 22:34
I'm closing this ticket. If after a thorough traffic analysis you come to a conclusion that the gateway doesn't behave as expected, please open a new ticket.

**Closed by arobenko** 2024-09-03 22:34 UTC

**Comment by arobenko** [comment] 2024-09-05 21:50
That makes sense. The MQTT v3.1.1 doesn't have an ability to change a will on the fly, requiring disconnection and re-connection from the gateway. However, the client should set its will through the connection procedure, rather than updating it after the connection is established. It will result in a single connection to the broker without reconnection later.
